---
title: "Lab 8"
author: "Jenny Balmagia"
date: "May 22, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Load Packages 
library(tidyverse)
library(raster)
library(rgdal)
library(rasterVis)
library(maps)
library(rgeos)
library(RColorBrewer)
library(sp)
```

```{r}
##Setting up colors and plot views ###

# view some color palettes
# display.brewer.all()
# rainbow color scheme
cols = rev(colorRampPalette(brewer.pal(11, 'Spectral'))(255)) 

#setting smaller margins for plotting
par(mar=c(2,2,1,1))

```



```{r}
#Import Data

all_threats <- raster("full_modelnv.tif")
#all_threats in console to check CRS, and other metadata

all_spp <- raster("ca_curr_sp_rich.tif")

```



```{r}
#Explore All Threats Data - Visualize, Summary Stats, Setting Extent 

plot(all_threats, col=cols)

# add a landmap to your shapefile. the add=T argument tells R to add it to the existing plot.
# make sure you understand what the other arguments do
plot(all_threats,ext=extent(-130,-110,24,50),col=cols) #extent zooms into a region
map('world',fill=T,add=T,col='gray')

plot(all_threats, col=cols, ext=extent(-121,-117,32,35), main="Cumulative Threats") #setting extent for the Santa Barbara Channel

#Explore raster cell values to look at how much of each threat level present, gives distribution of data
hist(all_threats, main="Cumulative Threats Frequency")

cellStats(all_threats,mean)#Mean raster cell value
cellStats(all_threats,sd) #Standard dev of mean

#Look at species data
plot(all_spp, col=cols)

```

Analysis Time!
Goal: Find Threat Hotspots
To do this, overlay the top 20% of cumulative threats with the top 20% of species richness
```{r}
#Step 1: Match Extents and Resolution: using crop() and resample()

#crop threats since its bigger
threats_crop <- crop(all_threats, all_spp)#crop threats to spp extent

#resample species raster to match resolution of threats layer (higher res)

# the method='ngb' argument specifies that we want to use a nearest neighbor algorithm to resample, instead of interpolation
spp_res <- resample(all_spp,threats_crop,method='ngb',progress='text')
# NOTE: the progress='text' argument is a great tool: it prints out the progress of a longer-running function into the console, so you can see how the operation is going

#Check the two layers line up decently with stack(), more useful for larger number of layers 

spp_threat_stack <- stack(threats_crop, spp_res)
plot(spp_threat_stack, col=cols)

```

```{r}
#Step 2: Reclassify to find top 20% in each layer

##SPECIES##
hist(spp_res, main= "Species raster values") #look at the data we're reclassifying

spp_res_na <- reclassify(spp_res, rcl=c(-Inf,0,NA)) #turn 0 into NA
hist(spp_res_na)#check it worked

#Find top 20% now
spp_cutoff <- quantile(spp_res_na, 0.8) #find the value of the 80th percentile
spp_maxVal <-cellStats(spp_res_na,max)#find maximum

#Make reclassification matrix
rcl_mat_spp <- c(-Inf,spp_cutoff,0,
                 spp_cutoff,spp_ma xVal,1)#Everything below cutoff is 0, everything above to the max value is 1 (top 20%)

#Apply to species layer
spp_binary <- reclassify(spp_res_na, rcl=rcl_mat_spp)

#Check our reclassification by plotting

binary_cols <- c("white","firebrick") #new color scheme for binary
plot(spp_binary, col=binary_cols, legend=F, main = "Top 20% Species Richness")
map('world', fill=T, add=T, col ='gray')
```

```{r}
#Step 2 for THREATS
##SPECIES##
hist(threats_crop, main= "threats raster values") #look at the data we're reclassifying

threats_crop_na <- reclassify(threats_crop, rcl=c(-Inf,0,NA)) #turn 0 into NA
hist(threats_crop_na)#check it worked

#Find top 20% now
threat_cutoff <- quantile(threats_crop_na, 0.8) #find the value of the 80th percentile
threat_maxVal <-cellStats(threats_crop_na,max)#find maximum

#Make reclassification matrix
rcl_mat_threats <- c(-Inf,threat_cutoff,0,
                 threat_cutoff,threat_maxVal,1)#Everything below cutoff is 0, everything above to the max value is 1 (top 20%)

#Apply to species layer
threat_binary <- reclassify(threats_crop_na, rcl=rcl_mat_threats)

#Check our reclassification by plotting

binary_cols <- c("white","firebrick") #new color scheme for binary
plot(threat_binary, col=binary_cols, legend=F, main = "Top 20% Cummulative Threats")
map('world', fill=T, add=T, col ='gray')

```


```{r}
#Step 3: Find Hotspots

hotspots <- overlay(spp_binary, threat_binary, fun = function(x,y){x+y})#addition so we can see overlap

#make colors for 3 breakpoints (cell values 0,1,2)
brks_hotspots <- seq(0,3,length.out = 4)
hotspot_cols <- c("white", "lightblue", "firebrick")

#plot hotspots
plot(hotspots, col = hotspot_cols, legend = F, main = "Hotspots"); map("world", fill=T, add=T, col = "gray80")

#Plot hotspots for SB channel extent
plot(hotspots, col = hotspot_cols, ext=extent(-121,-117,32,35), main= "Hotspots, SB Channel", legend=F)
map("world", fill=T, add=T, col="gray80")
```

All Species, Land-Based Water Quality Pollution threats

```{r}
#Read in rasters
nutrients <- raster("impact_nutrients.tif")
sed_increase <- raster("impact_sed_increase.tif")
sed_decrease <- raster("impact_sed_decrease.tif")
organic <- raster("impact_organic.tif")
inorganic <- raster("impact_inorganic.tif")

```


```{r}
#Explore and Visualize data, make it all same extent and resolution

plot(nutrients, col = cols, ext=extent(-121,-117,32,35))
plot(sed_increase, col = cols, ext=extent(-121,-117,32,35))
plot(sed_decrease, col = cols, ext=extent(-121,-117,32,35))
plot(organic, col = cols, ext=extent(-121,-117,32,35))
plot(inorganic, col = cols, ext=extent(-121,-117,32,35))

plot(spp_res, col = cols, ext=extent(-121,-117,32,35))


nut_crop <- crop(nutrients, spp_res)
sed_inc_crop <- crop(sed_increase, spp_res)
sed_dec_crop <- crop(sed_decrease, spp_res)
org_crop <- crop(organic, spp_res)
inorg_crop <- crop(inorganic, spp_res)

threat_crop_stack <- stack(nut_crop, sed_inc_crop, sed_dec_crop, org_crop,inorg_crop)

all_stack <- stack(threat_crop_stack, spp_res)


```



```{r}
#Re-assign 0s for all threat layers

nut_na <- reclassify(nut_crop, rcl = c(-Inf,0,NA))
sed_inc_na <- (reclassify(sed_inc_crop, rcl = c(-Inf,0,NA)))
sed_dec_na <- reclassify(sed_dec_crop, rcl = c(-Inf,0,NA))
org_na <- reclassify(org_crop, rcl = c(-Inf,0,NA))
inorg_na <- reclassify(inorg_crop, rcl = c(-Inf,0,NA))

#### Function to output a binary raster based on a user-given quantile (default is top 20%) ###
reclassify_topx <- function(rast,quant=0.8) {
  topx <- quantile(rast,quant) #find the 80% quantile of the raster values
  maxVal <- cellStats(rast,max) #find the maximum
  rcl <- c(-Inf,topx,0,
            topx,maxVal,1) # reclassify matrix (see help file for ?reclassify)
  out <- reclassify(rast,rcl=rcl)
  return(out) # returns the new binary raster
}

#Find top 20% of each layer, makes binary raster 

nut_binary <- reclassify_topx(nut_na)
sed_inc_binary <- reclassify_topx(sed_inc_na)
sed_dec_binary <- reclassify_topx(sed_dec_na)
org_binary <- reclassify_topx(org_na)
inorg_binary <- reclassify_topx(inorg_na)

#HOTSPOTS##
hotspots_allthreats <- overlay(nut_binary, sed_inc_binary,
                                sed_dec_binary, org_binary, 
                                inorg_binary, 
                                fun=function(a,b,c,d,e){a+b+c+d+e})

hotspots_spp_threats <- overlay(hotspots_allthreats,spp_binary,fun=function(x,y){x*y})

hotspot_cols_landthreats <- c("white","lightblue", "deeppink","darkorchid","darkgoldenrod1", "firebrick")

#Plot hotspots
plot(hotspots_spp_threats, col = hotspot_cols_landthreats,ext=extent(-121,-117,32,35),legend=T,main = "Hotspots");map("world", fill=T, add=T, col = "gray80")

plot(spp_binary,ext=extent(-121,-117,32,35));map("world", fill=T, add=T, col = "gray80")
```

